### ISSUE TITLE
Is this library ready for production?

### ISSUE THREAD

**Issue by Dhana-Krishnasamy** [Breeze/breeze.server.java#2]
Do you have any production users or its still in development?

Thanks

**Comment by steveschmitt** [comment]
It wasn't ready at the time of your question, but we feel that it is now.  It is as robust as the NHibernate support in the [breeze.server.net](https://github.com/Breeze/breeze.server.net) library, and shares some of the same code.

We know some production users of the Breeze NHibernate library, but we need to do some outreach in the Java community to learn about who is using breeze.server.java.
