### ISSUE TITLE
How to pre-save process (BeforeSaveEntities) the entities 

### ISSUE THREAD

**Issue by Dhana-Krishnasamy** [Breeze/breeze.server.java#3]
It looks like HibernateContext is hard wired inside SaveService. Thus I don't find a clean way to inject a Context into SaveService. Was SaveService meant to be inherited to inject new Context/HibernateContext? 
Thanks

**Comment by steveschmitt** [comment]
Sorry nobody replied to this.  The server implementation has changed significantly since you posted the question.  Take a look at the [SaveProcessor](http://breeze.github.io/doc-java-hib/save-processor.html) documentation for information about how to pre-process the entities before saving.
